Document: bogui
Title: Debian bogui Manual
Author: <insert document author here>
Abstract: This manual describes what bogui is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bogui/bogui.sgml.gz

Format: postscript
Files: /usr/share/doc/bogui/bogui.ps.gz

Format: text
Files: /usr/share/doc/bogui/bogui.text.gz

Format: HTML
Index: /usr/share/doc/bogui/html/index.html
Files: /usr/share/doc/bogui/html/*.html


