Document: qthello
Title: Debian qthello Manual
Author: <insert document author here>
Abstract: This manual describes what qthello is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qthello/qthello.sgml.gz

Format: postscript
Files: /usr/share/doc/qthello/qthello.ps.gz

Format: text
Files: /usr/share/doc/qthello/qthello.text.gz

Format: HTML
Index: /usr/share/doc/qthello/html/index.html
Files: /usr/share/doc/qthello/html/*.html


