Document: jmbreakout
Title: Debian jmbreakout Manual
Author: <insert document author here>
Abstract: This manual describes what jmbreakout is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/jmbreakout/jmbreakout.sgml.gz

Format: postscript
Files: /usr/share/doc/jmbreakout/jmbreakout.ps.gz

Format: text
Files: /usr/share/doc/jmbreakout/jmbreakout.text.gz

Format: HTML
Index: /usr/share/doc/jmbreakout/html/index.html
Files: /usr/share/doc/jmbreakout/html/*.html


